In [1]:
from utils import pipeline as pp
import pandas as pd
import glob
cnn=pp.get_conexion()
schema='egresados'
import numpy as np

In [2]:
df_benchmark=pd.read_sql_query('select agno, rbd, cod_ense, mrun from egresados.fact_egresados where egresado_flg=1',cnn)
df_benchmark

       agno    rbd  cod_ense      mrun
0      2011   2219       710    108578
1      2011   2219       710    317502
2      2011   2219       710    557110
3      2011   2219       710    573298
4      2011   2219       710    700528
...     ...    ...       ...       ...
22621  2023  25185       310  26951902
22622  2023  25185       310  26966725
22623  2023  25185       310  26988498
22624  2023  25185       310  27423366
22625  2023  25185       310  27580715

[22626 rows x 4 columns]

# **Pruebas de Admisión**

In [34]:
df_prueba=pd.read_csv('matricula_edsup/20230802_Matrícula_Ed_Superior_2012_PUBL_MRUN.csv',sep=';',encoding='utf8')
df_prueba=df_prueba[df_prueba['cat_periodo']==df_prueba['anio_ing_carr_ori']]
cols=['cat_periodo',  'mrun',
        'anio_ing_carr_ori', 
       'anio_ing_carr_act',  
       'tipo_inst_1'
       ,'tipo_inst_2',
       'tipo_inst_3'
       , 'cod_inst', 'nomb_inst', 
       'cod_carrera', 'nomb_carrera', 'modalidad', 'jornada',
       'dur_total_carr', 
         'nivel_carrera_1', 'nivel_carrera_2',
        'area_conocimiento',
       'cine_f_97_area', 'cine_f_97_subarea', 'area_carrera_generica',
       'cine_f_13_area', 'cine_f_13_subarea']
df_prueba=df_prueba.loc[:,cols]
df_prueba.dropna(subset=['mrun'],inplace=True)
df_prueba['mrun']=df_prueba['mrun'].astype('int64')
df_prueba.to_csv('bases/matricula_edsup/matricula_edsup_2012.csv')
df_prueba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 349753 entries, 3 to 1123195
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   cat_periodo            349753 non-null  int64
 1   mrun                   349753 non-null  int64
 2   anio_ing_carr_ori      349753 non-null  int64
 3   anio_ing_carr_act      96902 non-null   float64
 4   tipo_inst_1            349753 non-null  object
 5   tipo_inst_2            349753 non-null  object
 6   tipo_inst_3            349753 non-null  object
 7   cod_inst               349753 non-null  int64
 8   nomb_inst              349753 non-null  object
 9   cod_carrera            343686 non-null  float64
 10  nomb_carrera           349753 non-null  object
 11  modalidad              349753 non-null  object
 12  jornada                349753 non-null  object
 13  dur_total_carr         349753 non-null  int64
 14  nivel_carrera_1        349753 non-null  object
 15  nivel_carrera_2        349753 non-null  object
 16  area_conocimiento      349753 non-null  object
 17  cine_f_97_area         349753 non-null  object
 18  cine_f_97_subarea      349753 non-null  object
 19  area_carrera_generica  349753 non-null  object
 20  cine_f_13_area         349753 non-null  object
 21  cine_f_13_subarea      349753 non-null  object
dtypes: float64(2), int64(5), object(15)
memory usage: 61.4+ MB

In [38]:
lst_dfs=[]
for file in glob.glob('bases/matricula_edsup/*.csv'):
    lst_dfs.append(pd.read_csv(file,sep=','))
df_prueba=pd.concat(lst_dfs)
df_prueba.to_csv('matricula_edsup_2011_2023.csv',sep=';')

In [41]:
df_matricula_edsup=pd.merge(df_prueba,df_benchmark,how='inner',on=['mrun']).iloc[:,1:]
df_matricula_edsup

,cat_periodo,mrun,anio_ing_carr_ori,anio_ing_carr_act,tipo_inst_1,tipo_inst_2,tipo_inst_3,cod_inst,nomb_inst,cod_carrera,...,nivel_carrera_2,area_conocimiento,cine_f_97_area,cine_f_97_subarea,area_carrera_generica,cine_f_13_area,cine_f_13_subarea,agno,rbd,cod_ense
0,2012,9143,2012,NaN,Centros de Formación Técnica,Centros de Formación Técnica,Centros de Formación Técnica,430,CFT INACAP,135.0,...,Carreras Técnicas,Tecnología,"Ingeniería, Industria y Construcción",Ingeniería y Profesiones Afines,Técnico en Mecánica Automotriz,"Ingeniería, Industria y Construcción",Ingeniería y Profesiones Afines,2011,8644,510
1,2016,9143,2016,NaN,Institutos Profesionales,Institutos Profesionales,Institutos Profesionales,111,IP DUOC UC,23.0,...,Carreras Técnicas,Tecnología,Ciencias,Informática,Técnico en Computación e Informática,Tecnología de la Información y la Comunicación...,Tecnología de la Información y la Comunicación...,2011,8644,510
2,2018,9143,2018,2018.0,Institutos Profesionales,Institutos Profesionales,Institutos Profesionales,144,IP DE ARTE Y COMUNICACION ARCOS,49.0,...,Carreras Profesionales,Arte y Arquitectura,Humanidades y Artes,Artes,Diseño Gráfico,Artes y Humanidades,Artes,2011,8644,510
3,2012,14490,2012,NaN,Universidades,Universidades Privadas,Universidades Privadas,13,UNIVERSIDAD SANTO TOMAS,31.0,...,Carreras Profesionales,Salud,Salud y Servicios Sociales,Medicina,Kinesiología,Salud y Bienestar,Salud,2011,22191,310
4,2012,59968,2012,NaN,Universidades,Universidades Privadas,Universidades Privadas,39,UNIVERSIDAD SAN SEBASTIAN,39.0,...,Carreras Profesionales,Salud,Salud y Servicios Sociales,Medicina,Fonoaudiología,Salud y Bienestar,Salud,2011,22434,310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21150,2023,27085124,2023,2023.0,Centros de Formación Técnica,Centros de Formación Técnica,Centros de Formación Técnica,218,CFT DE ENAC,151.0,...,Carreras Técnicas,Tecnología,"Ingeniería, Industria y Construcción",Arquitectura y Construcción,Técnico en Construcción y Obras Civiles,"Ingeniería, Industria y Construcción",Arquitectura y Construcción,2022,8625,510
21151,2023,27085719,2023,2023.0,Universidades,Universidades Privadas,Universidades Privadas,20,UNIVERSIDAD ANDRES BELLO,111.0,...,Carreras Profesionales,Tecnología,"Ingeniería, Industria y Construcción",Ingeniería y Profesiones Afines,"Ingeniería Civil, plan común y licenciatura en...","Ingeniería, Industria y Construcción",Ingeniería y Profesiones Afines,2022,8676,310
21152,2023,27086817,2023,2023.0,Institutos Profesionales,Institutos Profesionales,Institutos Profesionales,100,IP INACAP,302.0,...,Carreras Profesionales,Tecnología,Ciencias,Informática,Ingeniería en Computación e Informática,Tecnología de la Información y la Comunicación...,Tecnología de la Información y la Comunicación...,2022,8644,510
21153,2023,27086990,2023,2023.0,Institutos Profesionales,Institutos Profesionales,Institutos Profesionales,143,IP AIEP,9.0,...,Carreras Técnicas,Administración y Comercio,"Ciencias Sociales, Enseñanza Comercial y Derecho",Enseñanza Comercial y Administración,Técnico en Contabilidad General,Administración de Empresas y Derecho,Educación Comercial y Administración,2022,8644,510
21154,2023,27134308,2023,2023.0,Centros de Formación Técnica,Centros de Formación Técnica,Centros de Formación Técnica,430,CFT INACAP,144.0,...,Carreras Técnicas,Salud,Salud y Servicios Sociales,Medicina,Técnico en Farmacia,Salud y Bienestar,Salud,2022,8625,510

In [42]:
tabla='matricula_edsup'
pp.insert_table(cnn,schema, tabla,df_matricula_edsup)

La tabla <<egresados.matricula_edsup>> no existe, omitiendo